### ISSUE TITLE
Szoftverspecifikáció elkészítése

### ISSUE THREAD

**Issue by timtim199** [Vizsgaremek-borosd-dekanycs/srs-docs#2]
SRS: Software Requirment Specification

- [ ] 1. Vizsgaremek-borosd-dekanycs/srs-docs#3
- [ ] 2. Vizsgaremek-borosd-dekanycs/srs-docs#4
- [ ] 3. Vizsgaremek-borosd-dekanycs/srs-docs#5
- [ ] 4. Vizsgaremek-borosd-dekanycs/srs-docs#6
- [ ] 5. Vizsgaremek-borosd-dekanycs/srs-docs#1

Segítség: https://asana.com/resources/software-requirement-document-template

**Comment by timtim199** [comment]
https://pdf.usaid.gov/pdf_docs/Pnacu897.pdf
